import { useState } from 'react';
import { Pressable, ScrollView, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { ApiError } from '../../../src/api/client';
import { completeProfile } from '../../../src/api/profile';
import { generateProgram } from '../../../src/api/programs';
import { WizardStepScreen } from '../../../src/components/wizard/WizardStepScreen';
import { CARDIO_PREFERENCE_LABELS, EQUIPMENT_LABELS, GOAL_LABELS, INJURY_FLAG_LABELS, NUTRITION_HABITS_LABELS, OCCUPATION_TYPE_LABELS, RECOVERY_QUALITY_LABELS, SEX_LABELS, SUPPLEMENT_LABELS, TRAINING_LEVEL_LABELS, getLabel, getLabelList, getWizardStepNumber, getWizardTotalSteps } from '../../../src/constants/wizardLabels';
import { RunpuyCard, RunpuyText } from '../../../src/design-system/components';
import { darkTheme } from '../../../src/design-system/themes';
import { layout, radii, spacing } from '../../../src/design-system/tokens';
import { useAuthStore } from '../../../src/store/authStore';
import { useWizardDraftStore } from '../../../src/store/wizardDraftStore';
import { resetWizardDraft } from '../../../src/store/wizardHydrate';

const t=darkTheme;
const Row=({label,value,last=false}:{label:string;value:string;last?:boolean})=><>{<View style={s.row}><RunpuyText theme={t} variant="caption" tone="secondary" style={s.label}>{label}</RunpuyText><RunpuyText theme={t} variant="caption" style={s.value}>{value}</RunpuyText></View>}{!last&&<View style={s.line}/>}</>;
const Head=({icon,title}:{icon:React.ComponentProps<typeof Feather>['name'];title:string})=><View style={s.head}><Feather name={icon} size={spacing.md} color={t.colors.textSecondary}/><RunpuyText accessibilityRole="header" theme={t} variant="caption">{title}</RunpuyText></View>;
const days=(n:number|null)=>n===null?'Not provided':n===1?'1 day/week':String(n)+' days/week';
const meals=(n:number|null)=>n===null?'Not provided':n===1?'1 meal/day':String(n)+' meals/day';

export default function WizardStepEighteenScreen(){
 const router=useRouter(); const logout=useAuthStore(x=>x.logout); const draft=useWizardDraftStore();
 const totalSteps=getWizardTotalSteps(draft.supplementUse); const currentStep=getWizardStepNumber(18,draft.supplementUse);
 const [isGenerating,setIsGenerating]=useState(false); const [errorMessage,setErrorMessage]=useState<string|null>(null); const [showGoHomeAction,setShowGoHomeAction]=useState(false); const [isOverflowOpen,setIsOverflowOpen]=useState(false);
 const backDestination=draft.injuryFlags.includes('none')||draft.injuryFlags.length===0?'/(profile)/wizard/step-16':'/(profile)/wizard/step-17';
 const onBack=()=>{if(isGenerating)return;router.replace(backDestination);}; const onLogout=async()=>{await logout();router.replace('/(auth)/login');};
 function getGenerationErrorMessage(error:unknown):string { if(!(error instanceof ApiError))return 'Something went wrong while generating your program. Please try again.'; if(error.status===0)return "Couldn't reach the server. Check your connection and try again."; if(error.status===401)return 'Your session expired. Please log in again.'; if(error.status===404)return "We couldn't find your profile. Please try again."; if(error.status===400)return "Your profile isn't fully complete yet. Please review your answers."; if(error.status===409)return 'You already have an active program.'; if(error.status===422)return "We couldn't build a program with your current equipment and injury settings. Try adjusting your profile and retrying."; return 'Something went wrong while generating your program. Please try again.'; }
 const onCreateProgram=async()=>{if(isGenerating)return;setIsGenerating(true);setErrorMessage(null);setShowGoHomeAction(false);try{await completeProfile();await generateProgram();resetWizardDraft();router.replace('/');}catch(error){setErrorMessage(getGenerationErrorMessage(error));setShowGoHomeAction(error instanceof ApiError&&error.status===409);}setIsGenerating(false);};
 const other=draft.supplementUse.includes('other')&&!!draft.supplementOther, notes=!!draft.injuryNotes;
 return <WizardStepScreen title="Your fitness profile is ready" subtitle="Review your answers, then we'll build your training program." currentStep={currentStep} totalSteps={totalSteps} primaryActionLabel={isGenerating?'Building your program':'Build My AI Program'} onPrimaryAction={onCreateProgram} primaryActionLoading={isGenerating} onBack={onBack} backDisabled={isGenerating} backAccessibilityLabel="Go back to review your previous answers" footer={<Footer open={isOverflowOpen} toggle={()=>setIsOverflowOpen(v=>!v)} logout={onLogout}/>}>
 <View style={s.body}><RunpuyCard theme={t} style={s.card}><ScrollView style={s.scroll} contentContainerStyle={s.content} showsVerticalScrollIndicator bounces={false}><Head icon="activity" title="TRAINING"/><Row label="Goal" value={getLabel(GOAL_LABELS,draft.goal)}/><Row label="Training level" value={getLabel(TRAINING_LEVEL_LABELS,draft.trainingLevel)}/><Row label="Training days" value={days(draft.trainingDaysPerWeek)}/><Row label="Session duration" value={draft.sessionDurationMin!==null?String(draft.sessionDurationMin)+' minutes':'Not provided'}/><Row label="Equipment" value={getLabelList(EQUIPMENT_LABELS,draft.equipmentAccess)} last/><View style={s.divider}/><Head icon="user" title="BODY"/><Row label="Age" value={draft.age!==null?String(draft.age):'Not provided'}/><Row label="Sex" value={getLabel(SEX_LABELS,draft.sex)}/><Row label="Height" value={draft.heightCm!==null?String(draft.heightCm)+' cm':'Not provided'}/><Row label="Weight" value={draft.weightKg!==null?String(draft.weightKg)+' kg':'Not provided'} last/><View style={s.divider}/><Head icon="coffee" title="LIFESTYLE & NUTRITION"/><Row label="Daily activity" value={getLabel(OCCUPATION_TYPE_LABELS,draft.occupationType)}/><Row label="Nutrition habits" value={getLabel(NUTRITION_HABITS_LABELS,draft.nutritionHabits)}/><Row label="Meal frequency" value={meals(draft.mealFrequency)}/><Row label="Cardio preference" value={getLabel(CARDIO_PREFERENCE_LABELS,draft.cardioPreference)}/><Row label="Supplements" value={getLabelList(SUPPLEMENT_LABELS,draft.supplementUse)} last={!other}/>{other&&<Row label="Other supplements" value={draft.supplementOther!} last/>}<View style={s.divider}/><Head icon="shield" title="RECOVERY & SAFETY"/><Row label="Recovery quality" value={getLabel(RECOVERY_QUALITY_LABELS,draft.recoveryQuality)}/><Row label="Injuries & limitations" value={getLabelList(INJURY_FLAG_LABELS,draft.injuryFlags)} last={!notes}/>{notes&&<Row label="Injury notes" value={draft.injuryNotes!} last/>}</ScrollView></RunpuyCard>{isGenerating&&<RunpuyText accessibilityLiveRegion="polite" theme={t} variant="caption" tone="secondary">Building your program...</RunpuyText>}{errorMessage&&<RunpuyText accessibilityRole="alert" theme={t} variant="caption" style={s.error}>{errorMessage}</RunpuyText>}{showGoHomeAction&&<Pressable accessibilityRole="button" accessibilityLabel="Go to home screen" onPress={()=>router.replace('/')} style={s.home}><RunpuyText theme={t} variant="body">Go to Home</RunpuyText></Pressable>}</View></WizardStepScreen>;
}
function Footer({open,toggle,logout}:{open:boolean;toggle:()=>void;logout:()=>void|Promise<void>}){return <View style={s.footer}><Pressable accessibilityRole="button" accessibilityLabel="More onboarding options" accessibilityState={{expanded:open}} onPress={toggle} style={s.more}><Feather name="more-horizontal" size={spacing.xl} color={t.colors.textSecondary}/></Pressable>{open&&<Pressable accessibilityRole="button" accessibilityLabel="Log out" onPress={logout} style={s.logout}><RunpuyText theme={t} variant="caption" tone="secondary">Log out</RunpuyText></Pressable>}<View style={s.privacy}><Feather name="lock" size={spacing.md} color={t.colors.textSecondary}/><RunpuyText theme={t} variant="caption" tone="secondary">Your answers are private and secure.</RunpuyText></View></View>}
const s={body:{flex:1,gap:spacing.md},card:{flex:1,padding:0},scroll:{flex:1},content:{padding:spacing.lg},head:{alignItems:'center',flexDirection:'row',gap:spacing.sm,marginBottom:spacing.sm},divider:{backgroundColor:t.colors.borderSubtle,height:1,marginVertical:spacing.lg},row:{alignItems:'flex-start',flexDirection:'row',gap:spacing.md,paddingVertical:spacing.sm},label:{flex:2},value:{flex:3,textAlign:'right'},line:{backgroundColor:t.colors.borderSubtle,height:1},error:{color:t.colors.error},home:{alignItems:'center',alignSelf:'flex-start',justifyContent:'center',minHeight:layout.minimumTouchTarget,paddingHorizontal:spacing.md},footer:{alignItems:'center',gap:spacing.sm},more:{alignItems:'center',justifyContent:'center',minHeight:layout.minimumTouchTarget,minWidth:layout.minimumTouchTarget},logout:{borderColor:t.colors.borderSubtle,borderRadius:radii.control,borderWidth:1,paddingHorizontal:spacing.md,paddingVertical:spacing.sm},privacy:{alignItems:'center',flexDirection:'row',gap:spacing.sm,justifyContent:'center'}} as const;
