export const GENERATOR_VERSION = "1.0";

const GOAL_LABELS = {
  hypertrophy: "Hypertrophy",
  strength: "Strength",
  fat_loss: "Fat Loss",
  recomposition: "Recomposition",
};

function titleCase(value) {
  return value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function getRealInjuryFlags(injuryFlags) {
  return (injuryFlags || []).filter((flag) => flag && flag !== "none");
}

export function buildExplanation({ splitResult, profile, diagnostics }) {
  const parts = [];
  const goalLabel = GOAL_LABELS[profile.goal] || profile.goal;
  const trainingLevelLabel = titleCase(profile.trainingLevel);
  const recoveryQualityLabel = titleCase(profile.recoveryQuality);
  const equipmentList = (profile.equipmentAccess || []).join(", ");
  const realInjuryFlags = getRealInjuryFlags(profile.injuryFlags);
  const totalScheduledDays =
    splitResult.numberOfTrainingDays + (splitResult.recoveryOrCardioDay ? 1 : 0);

  parts.push(`${goalLabel} program for a ${trainingLevelLabel} trainee.`);
  parts.push(
    `Scheduled for ${splitResult.numberOfTrainingDays} resistance-training day(s) across ${totalScheduledDays} total calendar day(s).`
  );

  if (splitResult.recoveryOrCardioDay) {
    parts.push("Includes one recovery_or_cardio day with no ProgramDayExercise rows in this phase.");
  }

  parts.push(`Recovery quality: ${recoveryQualityLabel}.`);

  if (splitResult.recoveryAdjusted) {
    parts.push("Split selection was recovery-adjusted to reduce weekly training stress.");
  }

  parts.push(`Equipment adaptation: ${equipmentList}.`);

  if (realInjuryFlags.length > 0) {
    parts.push(`Injury adaptations applied for: ${realInjuryFlags.join(", ")}.`);
  }

  if ((diagnostics || []).length > 0) {
    const diagnosticText = diagnostics
      .map(
        (diagnostic) =>
          `${diagnostic.dayType}/${diagnostic.movementPattern}: ${diagnostic.reason}`
      )
      .join(" | ");
    parts.push(`Accessory omissions: ${diagnosticText}.`);
  }

  parts.push(`Generated by AI-Fitness-Coach Program Generator v${GENERATOR_VERSION}`);

  return parts.join(" ");
}
