function deepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) {
    return value;
  }

  Object.freeze(value);
  for (const nestedValue of Object.values(value)) {
    deepFreeze(nestedValue);
  }
  return value;
}

function createFixture(name, source, exercise) {
  return deepFreeze({
    name,
    source,
    exercise,
  });
}

function catalogFixture(name, exercise) {
  return createFixture(name, "catalog", exercise);
}

function syntheticFixture(name, exercise) {
  return createFixture(name, "synthetic", exercise);
}

export const EXERCISE_SIMILARITY_CALIBRATION_FIXTURES_BY_NAME = deepFreeze({
  "Back Squat": catalogFixture("Back Squat", {
    exerciseId: 13,
    slug: "back-squat",
    dnaMovementPattern: "squat",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["barbell", "rack"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Front Squat": catalogFixture("Front Squat", {
    exerciseId: 51,
    slug: "front-squat",
    dnaMovementPattern: "squat",
    complexity: "compound",
    primaryMuscles: ["چهارسر"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["barbell", "rack"],
    difficulty: "advanced",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Bodyweight Squat (Controlled Range)": catalogFixture("Bodyweight Squat (Controlled Range)", {
    exerciseId: 52,
    slug: "bodyweight-squat-controlled-range",
    dnaMovementPattern: "squat",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  Deadlift: catalogFixture("Deadlift", {
    exerciseId: 14,
    slug: "deadlift",
    dnaMovementPattern: "hinge",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["پشت ران", "سرینی"],
    requiredEquipment: ["barbell"],
    difficulty: "advanced",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Romanian Deadlift": catalogFixture("Romanian Deadlift", {
    exerciseId: 23,
    slug: "romanian-deadlift",
    dnaMovementPattern: "hinge",
    complexity: "compound",
    primaryMuscles: ["پشت ران"],
    secondaryMuscles: ["سرینی", "کمر"],
    requiredEquipment: ["barbell"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Dumbbell Romanian Deadlift": catalogFixture("Dumbbell Romanian Deadlift", {
    exerciseId: 32,
    slug: "dumbbell-romanian-deadlift",
    dnaMovementPattern: "hinge",
    complexity: "compound",
    primaryMuscles: ["پشت ران"],
    secondaryMuscles: ["سرینی", "کمر"],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Hip Thrust": catalogFixture("Hip Thrust", {
    exerciseId: 33,
    slug: "hip-thrust",
    dnaMovementPattern: "hip_extension",
    complexity: "compound",
    primaryMuscles: ["سرینی"],
    secondaryMuscles: ["پشت ران", "کور"],
    requiredEquipment: ["barbell", "bench"],
    difficulty: "intermediate",
    stabilityDemand: "MODERATE",
    axialLoading: "LOW",
  }),
  "Glute Bridge": catalogFixture("Glute Bridge", {
    exerciseId: 31,
    slug: "glute-bridge",
    dnaMovementPattern: "hip_extension",
    complexity: "compound",
    primaryMuscles: ["سرینی"],
    secondaryMuscles: ["پشت ران", "کور"],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Leg Press": catalogFixture("Leg Press", {
    exerciseId: 24,
    slug: "leg-press",
    dnaMovementPattern: "squat",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی"],
    requiredEquipment: ["leg_press_machine"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "LOW",
  }),
  "Lunge": catalogFixture("Lunge", {
    exerciseId: 20,
    slug: "lunge",
    dnaMovementPattern: "lunge",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "HIGH",
    axialLoading: "LOW",
  }),
  "Bodyweight Reverse Lunge": catalogFixture("Bodyweight Reverse Lunge", {
    exerciseId: 29,
    slug: "bodyweight-reverse-lunge",
    dnaMovementPattern: "lunge",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "HIGH",
    axialLoading: "NONE",
  }),
  "Dumbbell Reverse Lunge": catalogFixture("Dumbbell Reverse Lunge", {
    exerciseId: 30,
    slug: "dumbbell-reverse-lunge",
    dnaMovementPattern: "lunge",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "HIGH",
    axialLoading: "LOW",
  }),
  "Step-Up": catalogFixture("Step-Up", {
    exerciseId: 34,
    slug: "step-up",
    dnaMovementPattern: "single_leg",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["step_platform"],
    difficulty: "beginner",
    stabilityDemand: "HIGH",
    axialLoading: "NONE",
  }),
  "Dumbbell Step-Up": catalogFixture("Dumbbell Step-Up", {
    exerciseId: 35,
    slug: "dumbbell-step-up",
    dnaMovementPattern: "single_leg",
    complexity: "compound",
    primaryMuscles: ["پا"],
    secondaryMuscles: ["سرینی", "کور"],
    requiredEquipment: ["dumbbell", "step_platform"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "LOW",
  }),
  "Bench Press": catalogFixture("Bench Press", {
    exerciseId: 15,
    slug: "bench-press",
    dnaMovementPattern: "horizontal_press",
    complexity: "compound",
    primaryMuscles: ["سینه"],
    secondaryMuscles: ["سرشانه", "پشت بازو"],
    requiredEquipment: ["barbell", "bench", "rack"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  "Dumbbell Bench Press": catalogFixture("Dumbbell Bench Press", {
    exerciseId: 37,
    slug: "dumbbell-bench-press",
    dnaMovementPattern: "horizontal_press",
    complexity: "compound",
    primaryMuscles: ["سینه"],
    secondaryMuscles: ["سرشانه", "پشت بازو"],
    requiredEquipment: ["dumbbell", "bench"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  "Machine Chest Press": catalogFixture("Machine Chest Press", {
    exerciseId: 38,
    slug: "machine-chest-press",
    dnaMovementPattern: "horizontal_press",
    complexity: "compound",
    primaryMuscles: ["سینه"],
    secondaryMuscles: ["سرشانه", "پشت بازو"],
    requiredEquipment: ["selectorized_machine"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Push-Up": catalogFixture("Push-Up", {
    exerciseId: 36,
    slug: "push-up",
    dnaMovementPattern: "horizontal_press",
    complexity: "compound",
    primaryMuscles: ["سینه"],
    secondaryMuscles: ["سرشانه", "پشت بازو", "کور"],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  "Overhead Press": catalogFixture("Overhead Press", {
    exerciseId: 17,
    slug: "overhead-press",
    dnaMovementPattern: "vertical_press",
    complexity: "compound",
    primaryMuscles: ["سرشانه"],
    secondaryMuscles: ["پشت بازو", "کور"],
    requiredEquipment: ["barbell"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Dumbbell Shoulder Press": catalogFixture("Dumbbell Shoulder Press", {
    exerciseId: 39,
    slug: "dumbbell-shoulder-press",
    dnaMovementPattern: "vertical_press",
    complexity: "compound",
    primaryMuscles: ["سرشانه"],
    secondaryMuscles: ["پشت بازو", "کور"],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "LOW",
  }),
  "Machine Shoulder Press": catalogFixture("Machine Shoulder Press", {
    exerciseId: 40,
    slug: "machine-shoulder-press",
    dnaMovementPattern: "vertical_press",
    complexity: "compound",
    primaryMuscles: ["سرشانه"],
    secondaryMuscles: ["پشت بازو"],
    requiredEquipment: ["selectorized_machine"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "LOW",
  }),
  "Pike Push-Up": catalogFixture("Pike Push-Up", {
    exerciseId: 41,
    slug: "pike-push-up",
    dnaMovementPattern: "vertical_press",
    complexity: "compound",
    primaryMuscles: ["سرشانه"],
    secondaryMuscles: ["پشت بازو", "کور"],
    requiredEquipment: ["bodyweight"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "LOW",
  }),
  "Pull-Up": catalogFixture("Pull-Up", {
    exerciseId: 16,
    slug: "pull-up",
    dnaMovementPattern: "vertical_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو", "کور"],
    requiredEquipment: ["pull_up_bar"],
    difficulty: "intermediate",
    stabilityDemand: "MODERATE",
    axialLoading: "LOW",
  }),
  "Lat Pulldown": catalogFixture("Lat Pulldown", {
    exerciseId: 42,
    slug: "lat-pulldown",
    dnaMovementPattern: "vertical_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو"],
    requiredEquipment: ["selectorized_machine"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Cable Pulldown": catalogFixture("Cable Pulldown", {
    exerciseId: 43,
    slug: "cable-pulldown",
    dnaMovementPattern: "vertical_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو"],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Weighted Pull-Up": catalogFixture("Weighted Pull-Up", {
    exerciseId: 44,
    slug: "weighted-pull-up",
    dnaMovementPattern: "vertical_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو", "کور"],
    requiredEquipment: [],
    difficulty: "advanced",
    stabilityDemand: null,
    axialLoading: null,
  }),
  "Barbell Row": catalogFixture("Barbell Row", {
    exerciseId: 28,
    slug: "barbell-row",
    dnaMovementPattern: "horizontal_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو", "کمر"],
    requiredEquipment: ["barbell"],
    difficulty: "advanced",
    stabilityDemand: "HIGH",
    axialLoading: "HIGH",
  }),
  "Cable Row": catalogFixture("Cable Row", {
    exerciseId: 27,
    slug: "cable-row",
    dnaMovementPattern: "horizontal_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو"],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Bodyweight Inverted Row": catalogFixture("Bodyweight Inverted Row", {
    exerciseId: 25,
    slug: "bodyweight-inverted-row",
    dnaMovementPattern: "horizontal_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو", "کور"],
    requiredEquipment: [],
    difficulty: "beginner",
    stabilityDemand: null,
    axialLoading: null,
  }),
  "Dumbbell Row": catalogFixture("Dumbbell Row", {
    exerciseId: 26,
    slug: "dumbbell-row",
    dnaMovementPattern: "horizontal_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو", "کمر"],
    requiredEquipment: [],
    difficulty: "beginner",
    stabilityDemand: null,
    axialLoading: null,
  }),
  "Cable Curl": catalogFixture("Cable Curl", {
    exerciseId: 45,
    slug: "cable-curl",
    dnaMovementPattern: "elbow_flexion",
    complexity: "isolation",
    primaryMuscles: ["بازو"],
    secondaryMuscles: [],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Dumbbell Curl": catalogFixture("Dumbbell Curl", {
    exerciseId: 18,
    slug: "dumbbell-curl",
    dnaMovementPattern: "elbow_flexion",
    complexity: "isolation",
    primaryMuscles: ["بازو"],
    secondaryMuscles: [],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Cable Pushdown": catalogFixture("Cable Pushdown", {
    exerciseId: 19,
    slug: "cable-pushdown",
    dnaMovementPattern: "elbow_extension",
    complexity: "isolation",
    primaryMuscles: ["بازو"],
    secondaryMuscles: [],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Bench Dip": catalogFixture("Bench Dip", {
    exerciseId: 47,
    slug: "bench-dip",
    dnaMovementPattern: "elbow_extension",
    complexity: "isolation",
    primaryMuscles: ["پشت بازو"],
    secondaryMuscles: ["سینه", "سرشانه"],
    requiredEquipment: ["bench"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Machine Leg Curl": catalogFixture("Machine Leg Curl", {
    exerciseId: 50,
    slug: "machine-leg-curl",
    dnaMovementPattern: "knee_flexion",
    complexity: "isolation",
    primaryMuscles: ["پشت ران"],
    secondaryMuscles: [],
    requiredEquipment: ["selectorized_machine"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Crunch": catalogFixture("Crunch", {
    exerciseId: 21,
    slug: "crunch",
    dnaMovementPattern: "trunk_flexion",
    complexity: "isolation",
    primaryMuscles: ["شکم"],
    secondaryMuscles: [],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Cable Crunch": catalogFixture("Cable Crunch", {
    exerciseId: 48,
    slug: "cable-crunch",
    dnaMovementPattern: "trunk_flexion",
    complexity: "isolation",
    primaryMuscles: ["شکم"],
    secondaryMuscles: ["کور"],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Plank": catalogFixture("Plank", {
    exerciseId: 22,
    slug: "plank",
    dnaMovementPattern: "anti_extension",
    complexity: "isolation",
    primaryMuscles: ["کور"],
    secondaryMuscles: ["شکم", "سرشانه"],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  "Dead Bug": catalogFixture("Dead Bug", {
    exerciseId: 49,
    slug: "dead-bug",
    dnaMovementPattern: "anti_extension",
    complexity: "isolation",
    primaryMuscles: ["کور"],
    secondaryMuscles: ["شکم"],
    requiredEquipment: ["bodyweight"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  "Cable Pallof Press": catalogFixture("Cable Pallof Press", {
    exerciseId: 54,
    slug: "cable-pallof-press",
    dnaMovementPattern: "anti_rotation",
    complexity: "isolation",
    primaryMuscles: ["کور"],
    secondaryMuscles: ["شکم", "سرشانه"],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "NONE",
  }),
  "Cable Single-Leg Hip Extension": catalogFixture("Cable Single-Leg Hip Extension", {
    exerciseId: 53,
    slug: "cable-single-leg-hip-extension",
    dnaMovementPattern: "hip_extension",
    complexity: "compound",
    primaryMuscles: ["سرینی"],
    secondaryMuscles: ["کور", "پشت ران"],
    requiredEquipment: ["cable"],
    difficulty: "beginner",
    stabilityDemand: "HIGH",
    axialLoading: "NONE",
  }),
  "Leg Extension (Synthetic)": syntheticFixture("Leg Extension (Synthetic)", {
    exerciseId: 9001,
    slug: "leg-extension-synthetic",
    dnaMovementPattern: "knee_extension",
    complexity: "isolation",
    primaryMuscles: ["چهارسر"],
    secondaryMuscles: [],
    requiredEquipment: ["selectorized_machine"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Lateral Raise (Synthetic)": syntheticFixture("Lateral Raise (Synthetic)", {
    exerciseId: 9002,
    slug: "lateral-raise-synthetic",
    dnaMovementPattern: "shoulder_abduction",
    complexity: "isolation",
    primaryMuscles: ["سرشانه"],
    secondaryMuscles: [],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Goblet Squat (Synthetic)": syntheticFixture("Goblet Squat (Synthetic)", {
    exerciseId: 9003,
    slug: "goblet-squat-synthetic",
    dnaMovementPattern: "squat",
    complexity: "compound",
    primaryMuscles: ["چهارسر", "سرینی"],
    secondaryMuscles: ["کور"],
    requiredEquipment: ["dumbbell"],
    difficulty: "beginner",
    stabilityDemand: "MODERATE",
    axialLoading: "LOW",
  }),
  "Chest-Supported Dumbbell Row (Synthetic)": syntheticFixture("Chest-Supported Dumbbell Row (Synthetic)", {
    exerciseId: 9004,
    slug: "chest-supported-dumbbell-row-synthetic",
    dnaMovementPattern: "horizontal_pull",
    complexity: "compound",
    primaryMuscles: ["پشت"],
    secondaryMuscles: ["بازو"],
    requiredEquipment: ["dumbbell", "bench"],
    difficulty: "beginner",
    stabilityDemand: "LOW",
    axialLoading: "NONE",
  }),
  "Chin-Up (Synthetic)": syntheticFixture("Chin-Up (Synthetic)", {
    exerciseId: 9005,
    slug: "chin-up-synthetic",
    dnaMovementPattern: "vertical_pull",
    complexity: "compound",
    primaryMuscles: ["پشت", "بازو"],
    secondaryMuscles: ["کور"],
    requiredEquipment: ["pull_up_bar"],
    difficulty: "intermediate",
    stabilityDemand: "MODERATE",
    axialLoading: "LOW",
  }),
  "Farmer Carry (Synthetic)": syntheticFixture("Farmer Carry (Synthetic)", {
    exerciseId: 9006,
    slug: "farmer-carry-synthetic",
    dnaMovementPattern: "carry",
    complexity: "compound",
    primaryMuscles: ["کور", "پشت"],
    secondaryMuscles: ["سرشانه", "بازو"],
    requiredEquipment: ["dumbbell"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "LOW",
  }),
  "Suitcase Carry (Synthetic)": syntheticFixture("Suitcase Carry (Synthetic)", {
    exerciseId: 9007,
    slug: "suitcase-carry-synthetic",
    dnaMovementPattern: "carry",
    complexity: "compound",
    primaryMuscles: ["کور", "پشت"],
    secondaryMuscles: ["سرشانه", "بازو"],
    requiredEquipment: ["dumbbell"],
    difficulty: "intermediate",
    stabilityDemand: "HIGH",
    axialLoading: "LOW",
  }),
  "Unknown Mobility Drill (Synthetic Partial)": syntheticFixture("Unknown Mobility Drill (Synthetic Partial)", {
    exerciseId: 9008,
    slug: "unknown-mobility-drill-synthetic-partial",
    dnaMovementPattern: null,
    complexity: null,
    primaryMuscles: [],
    secondaryMuscles: [],
    requiredEquipment: [],
    difficulty: null,
    stabilityDemand: null,
    axialLoading: null,
  }),
  "Unknown Isometric Hold (Synthetic Partial)": syntheticFixture("Unknown Isometric Hold (Synthetic Partial)", {
    exerciseId: 9009,
    slug: "unknown-isometric-hold-synthetic-partial",
    dnaMovementPattern: null,
    complexity: null,
    primaryMuscles: [],
    secondaryMuscles: [],
    requiredEquipment: [],
    difficulty: null,
    stabilityDemand: null,
    axialLoading: null,
  }),
});

export function resolveExerciseSimilarityCalibrationFixture(name) {
  const fixture = EXERCISE_SIMILARITY_CALIBRATION_FIXTURES_BY_NAME[name];
  if (!fixture) {
    throw new Error(`Unknown exercise similarity calibration fixture "${name}".`);
  }

  return fixture;
}

export const EXERCISE_SIMILARITY_CALIBRATION_FIXTURE_NAMES = deepFreeze(
  Object.keys(EXERCISE_SIMILARITY_CALIBRATION_FIXTURES_BY_NAME).sort((left, right) =>
    left.localeCompare(right, "en", { sensitivity: "base" })
  )
);
